
package dk.diku.pcsd.assignment1.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "KeyValueBaseImplService", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KeyValueBaseImplService {


    /**
     * 
     * @param arg0
     * @throws ServiceInitializingException_Exception
     * @throws ServiceAlreadyInitializedException_Exception
     * @throws FileNotFoundException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.InitResponse")
    public void init(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws FileNotFoundException_Exception, ServiceAlreadyInitializedException_Exception, ServiceInitializingException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.DeleteResponse")
    public void delete(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws KeyAlreadyPresentException_Exception
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "insert", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Insert")
    @ResponseWrapper(localName = "insertResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.InsertResponse")
    public void insert(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyAlreadyPresentException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws KeyNotFoundException_Exception
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "update", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.UpdateResponse")
    public void update(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ValueListImpl arg1)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns dk.diku.pcsd.assignment1.impl.ValueListImpl
     * @throws KeyNotFoundException_Exception
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "read", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Read")
    @ResponseWrapper(localName = "readResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.ReadResponse")
    public ValueListImpl read(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0)
        throws IOException_Exception, KeyNotFoundException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<dk.diku.pcsd.assignment1.impl.ValueListImpl>
     * @throws BeginGreaterThanEndException_Exception
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "scan", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.Scan")
    @ResponseWrapper(localName = "scanResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.ScanResponse")
    public List<ValueListImpl> scan(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        KeyImpl arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<dk.diku.pcsd.assignment1.impl.ValueListImpl>
     * @throws BeginGreaterThanEndException_Exception
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "atomicScan", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.AtomicScan")
    @ResponseWrapper(localName = "atomicScanResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.AtomicScanResponse")
    public List<ValueListImpl> atomicScan(
        @WebParam(name = "arg0", targetNamespace = "")
        KeyImpl arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        KeyImpl arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Predicate arg2)
        throws BeginGreaterThanEndException_Exception, IOException_Exception, ServiceNotInitializedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws IOException_Exception
     * @throws ServiceNotInitializedException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "bulkPut", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.BulkPut")
    @ResponseWrapper(localName = "bulkPutResponse", targetNamespace = "http://impl.assignment1.pcsd.diku.dk/", className = "dk.diku.pcsd.assignment1.impl.BulkPutResponse")
    public void bulkPut(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Pair> arg0)
        throws IOException_Exception, ServiceNotInitializedException_Exception
    ;

}
