
package dk.diku.pcsd.assignment3.slave.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "KeyValueBaseSlaveImplServiceService", targetNamespace = "http://impl.slave.assignment3.pcsd.diku.dk/", wsdlLocation = "http://localhost:8080/slave/keyvaluebaseslave?wsdl")
public class KeyValueBaseSlaveImplServiceService
    extends Service
{

    private final static URL KEYVALUEBASESLAVEIMPLSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dk.diku.pcsd.assignment3.slave.impl.KeyValueBaseSlaveImplServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dk.diku.pcsd.assignment3.slave.impl.KeyValueBaseSlaveImplServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/slave/keyvaluebaseslave?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/slave/keyvaluebaseslave?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        KEYVALUEBASESLAVEIMPLSERVICESERVICE_WSDL_LOCATION = url;
    }

    public KeyValueBaseSlaveImplServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyValueBaseSlaveImplServiceService() {
        super(KEYVALUEBASESLAVEIMPLSERVICESERVICE_WSDL_LOCATION, new QName("http://impl.slave.assignment3.pcsd.diku.dk/", "KeyValueBaseSlaveImplServiceService"));
    }

    /**
     * 
     * @return
     *     returns KeyValueBaseSlaveImplService
     */
    @WebEndpoint(name = "KeyValueBaseSlaveImplServicePort")
    public KeyValueBaseSlaveImplService getKeyValueBaseSlaveImplServicePort() {
        return super.getPort(new QName("http://impl.slave.assignment3.pcsd.diku.dk/", "KeyValueBaseSlaveImplServicePort"), KeyValueBaseSlaveImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyValueBaseSlaveImplService
     */
    @WebEndpoint(name = "KeyValueBaseSlaveImplServicePort")
    public KeyValueBaseSlaveImplService getKeyValueBaseSlaveImplServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.slave.assignment3.pcsd.diku.dk/", "KeyValueBaseSlaveImplServicePort"), KeyValueBaseSlaveImplService.class, features);
    }

}
