
package dk.diku.pcsd.assignment3.master.impl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "KeyValueBaseMasterImplServiceService", targetNamespace = "http://impl.master.assignment3.pcsd.diku.dk/", wsdlLocation = "http://localhost:8080/master/keyvaluebasemaster?wsdl")
public class KeyValueBaseMasterImplServiceService
    extends Service
{

    private final static URL KEYVALUEBASEMASTERIMPLSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(dk.diku.pcsd.assignment3.master.impl.KeyValueBaseMasterImplServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = dk.diku.pcsd.assignment3.master.impl.KeyValueBaseMasterImplServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/master/keyvaluebasemaster?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/master/keyvaluebasemaster?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        KEYVALUEBASEMASTERIMPLSERVICESERVICE_WSDL_LOCATION = url;
    }

    public KeyValueBaseMasterImplServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyValueBaseMasterImplServiceService() {
        super(KEYVALUEBASEMASTERIMPLSERVICESERVICE_WSDL_LOCATION, new QName("http://impl.master.assignment3.pcsd.diku.dk/", "KeyValueBaseMasterImplServiceService"));
    }

    /**
     * 
     * @return
     *     returns KeyValueBaseMasterImplService
     */
    @WebEndpoint(name = "KeyValueBaseMasterImplServicePort")
    public KeyValueBaseMasterImplService getKeyValueBaseMasterImplServicePort() {
        return super.getPort(new QName("http://impl.master.assignment3.pcsd.diku.dk/", "KeyValueBaseMasterImplServicePort"), KeyValueBaseMasterImplService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyValueBaseMasterImplService
     */
    @WebEndpoint(name = "KeyValueBaseMasterImplServicePort")
    public KeyValueBaseMasterImplService getKeyValueBaseMasterImplServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.master.assignment3.pcsd.diku.dk/", "KeyValueBaseMasterImplServicePort"), KeyValueBaseMasterImplService.class, features);
    }

}
